# Generated by Django 3.0.1 on 2020-01-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200107_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhashtag',
            name='card',
            field=models.ManyToManyField(to='cards.UserCard'),
        ),
    ]
